[pytest]
markers =
    slow: mark a test as slow
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Coverage settings
addopts =
    --cov=core
    --cov=timeseries
    --cov=visualizations
    --cov-report=html
    --cov-report=term-missing
    --doctest-modules
    -v

# Ignore these for doctests
doctest_optionflags = NORMALIZE_WHITESPACE ELLIPSIS